version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: ttt_db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: ttt_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"

volumes:
  pgdata: